### ISSUE TITLE
Construct README.md

### ISSUE THREAD

**Issue by EdvinArdo** [DD2480-Group17/assignment1#1]
Should contain the statement of what everyone has contributed.

**Comment by johannaii** [comment]
Guidelines for the README-file from the grading criteria:
https://yourbasic.org/algorithms/your-basic-api/#1-tell-me-what-this-thing-is

**Comment by EdvinArdo** [comment]
Remember to include documentation for required dependencies (java, junit, maven) and instructions for how to run tests (`mvn test)` and how to run main (`mvn -q exec:java -Dexec.mainClass="Decide" -Dexec.args="1"` where acceptable args are 1, 2 or 3)
