### ISSUE TITLE
Add an inputreader

### ISSUE THREAD

**Issue by Marcus9512** [DD2480-Group17/assignment1#21]
Implement a class that can read parameters from a file and store them in the class "Parameters"

Output: a object of type Parameters

**Comment by EdvinArdo** [comment]
Besides input for parameters I'll include input for points, lcm and puv

**Comment by EdvinArdo** [comment]
Implement reading from string in source code to enable tests that are not dependent on external files

**Comment by EdvinArdo** [comment]
Added in PR #23
