### ISSUE TITLE
Fix getters and setters in Decide class

### ISSUE THREAD

**Issue by georgewbar** [DD2480-Group17/assignment1#31]
Getters and setters are needed in Decide class and global fields need to be private.

**Comment by georgewbar** [comment]
I dont know if it is better to leave this to the last thing to do and see if we would have time for it. All the test cases will need to be changed to use setters and getters, which might take time but the functionality is still the same regardless whether getters and setters are implemented or not.

**Comment by Marcus9512** [comment]
Don´t think this is needed anymore, the refactor moved all those function to another class
