### ISSUE TITLE
Doc, review the documentation for each method

### ISSUE THREAD

**Issue by Marcus9512** [DD2480-Group17/assignment1#59]
All the documentation for each method in the program needs to be checked and corrected for typos.

**Comment by johannaii** [comment]
I think that the IOHandler class already has a good documentation, but I will wait and do a refactoring again if it is needed when we have finished the other issues.

**Comment by georgewbar** [comment]
Looks good.

**Comment by EdvinArdo** [comment]
Fixed in #75
